### PR TITLE
♻️ Refactor header option parser to use the standard library instead of a custom RegEx

### PR DESCRIPTION
**Pull request by tiangolo**
♻️ Refactor header option parser to use the standard library instead of a custom RegEx

This uses the internal standard library module to parse MIME type (Content-Type) parameters instead of using a manual RegEx.

With inspiration from Baize: https://github.com/abersheeran/baize/blob/174c21a044cdc69b637f70030c0aad2dc8be5de1/baize/utils.py#L39-L76 but instead of copy-pasting utils from the standard library, using the suggested approach in the PEP, using another utility.

Ref: https://peps.python.org/pep-0594/#cgi

### CODE REVIEW

**Review by Kludex — APPROVED** [review]

**Comment by darakian** [comment]
Hey @Kludex, random question but could I ask you to make a security advisory for `python-multipart` for the versions affected by this issue? We (github) have gotten asks over on https://github.com/github/advisory-database/pull/3479 to add your package as affected. We've got docs on advisories here
https://docs.github.com/en/code-security/security-advisories
but tl;dr if you click into the security tab you can make a new advisory in there.

Given that the issue discussed in the PR above is fundamentally rooted in this project we think it would be ideal if you would be willing to make an advisory 🙇

**Comment by Kludex** [comment]
I can't create advisories in this repository. I'm not the owner.

**Comment by Kludex** [comment]
I'll email the owner, and ask to be transferred.

**Comment by darakian** [comment]
Thank you much and sorry to bug 🙇

**Comment by andrew-d** [comment]
Also, apologies on my part for being absent here; I'm coordinating with @Kludex to transfer this repository to the [encode](https://github.com/encode) organization. I appreciate all the contributors that stepped in after I stopped being involved, and I'm excited to hand this off officially 😃

**Comment by Kludex** [comment]
@darakian I'll create the advisory today.

Do you know if advisories can be deleted from other repositories e.g. FastAPI and Starlette?

**Comment by darakian** [comment]
> @darakian I'll create the advisory here today.

Many thanks. I'll keep my eyes open for it 👀 

> Do you know if advisories can be deleted from other repositories e.g. FastAPI and Starlette?

They cannot. The best thing to do with those (IMO) is to make them specifically about which versions bundled the affected versions of `python-multipart`.

**Comment by Kludex** [comment]
So, if someone maliciously release an advisory for all versions of a package, without releasing a new version, there's nothing GitHub can do about it?

**Comment by levrik** [comment]
It seems that this change broke parsing of extended syntax for UTF-8 file names (e.g. `filename*=utf-8''`) as defined in https://www.rfc-editor.org/rfc/rfc5987.

**Comment by tiangolo** [comment]
@levrik yep, it was fixed in https://github.com/Kludex/python-multipart/pull/79 and released as 0.0.8.

**Pull request merged**
