### PR TITLE
Add get_header function

### PR DESCRIPTION
**Pull request by chemtrails**
These changes add support for lowercase, Capitalized and Pascal-Case headers.

### CODE REVIEW

**Comment by Kludex** [comment]
So... Why?

**Comment by chemtrails** [comment]
If you don't understand then I guess it doesn't belong here

**Comment by Kludex** [comment]
I can't understand if you are being rude, or if you think your change doesn't make sense.

If it's the second, you could have tried to explain.

If it's the first... Thanks for closing the issue. 👀

**Comment by chemtrails** [comment]
Neither, it's just a message for why I'm closing.

**Comment by chemtrails** [comment]
Do you want me to explain something specific?

**Pull request closed without merging**
